"""initial_schema

Revision ID: ce58f26a68b0
Revises: 
Create Date: 2026-09-05 16:22:22.955485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce58f26a68b0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_policies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('min_risk_score', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('max_risk_score', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('requires_manager', sa.Boolean(), nullable=False),
    sa.Column('requires_finance', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_tiers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_discount_limit', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('product_categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('subscription_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('billing_interval', sa.Enum('MONTHLY', 'QUARTERLY', 'YEARLY', name='billing_interval'), nullable=False),
    sa.Column('interval_count', sa.Integer(), nullable=False),
    sa.Column('proration_method', sa.Enum('DAILY_PRO_RATA', 'FULL_PERIOD', 'NO_PRORATION', name='proration_method'), nullable=False),
    sa.Column('cancellation_policy', sa.String(length=100), nullable=False),
    sa.Column('refund_policy', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warehouses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('shipping_cost_weight', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('replenishment_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouses_code'), 'warehouses', ['code'], unique=True)
    op.create_table('customers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('customer_tier_id', sa.Uuid(), nullable=False),
    sa.Column('billing_address', sa.Text(), nullable=True),
    sa.Column('shipping_address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_tier_id'], ['customer_tiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_customer_tier_id'), 'customers', ['customer_tier_id'], unique=False)
    op.create_table('discount_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_tier_id', sa.Uuid(), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('max_discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.ForeignKeyConstraint(['customer_tier_id'], ['customer_tiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discount_rules_category_id'), 'discount_rules', ['category_id'], unique=False)
    op.create_index(op.f('ix_discount_rules_customer_tier_id'), 'discount_rules', ['customer_tier_id'], unique=False)
    op.create_table('price_lists',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('customer_tier_id', sa.Uuid(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_tier_id'], ['customer_tiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_lists_customer_tier_id'), 'price_lists', ['customer_tier_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_subscription', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_table('inventory',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('quantity_on_hand', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity_reserved', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reorder_level', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reorder_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'product_id', name='uq_inventory_warehouse_product')
    )
    op.create_index(op.f('ix_inventory_product_id'), 'inventory', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_warehouse_id'), 'inventory', ['warehouse_id'], unique=False)
    op.create_table('product_variants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('attribute_name', sa.String(length=100), nullable=False),
    sa.Column('attribute_value', sa.String(length=100), nullable=False),
    sa.Column('extra_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.create_table('recommendation_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_product_id', sa.Uuid(), nullable=False),
    sa.Column('recommended_product_id', sa.Uuid(), nullable=False),
    sa.Column('rule_type', sa.Enum('UPSELL', 'CROSS_SELL', name='recommendation_type'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('promotion_tag', sa.String(length=100), nullable=True),
    sa.Column('min_margin_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('co_purchase_score', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('is_promoted', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recommended_product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['source_product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_rules_recommended_product_id'), 'recommendation_rules', ['recommended_product_id'], unique=False)
    op.create_index(op.f('ix_recommendation_rules_source_product_id'), 'recommendation_rules', ['source_product_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_customer_id'), 'users', ['customer_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('old_values', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('new_values', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_sessions_refresh_token_hash'), 'auth_sessions', ['refresh_token_hash'], unique=True)
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('price_list_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('price_list_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['price_list_id'], ['price_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_price_list_items_list_product', 'price_list_items', ['price_list_id', 'product_id'], unique=False)
    op.create_index(op.f('ix_price_list_items_price_list_id'), 'price_list_items', ['price_list_id'], unique=False)
    op.create_index(op.f('ix_price_list_items_product_id'), 'price_list_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_price_list_items_variant_id'), 'price_list_items', ['variant_id'], unique=False)
    op.create_table('quotations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quotation_number', sa.String(length=100), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('sales_rep_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'UNDER_NEGOTIATION', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'REVISION_REQUIRED', 'CONFIRMED', name='quotation_status'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('order_discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('margin_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('margin_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('current_approval_level', sa.String(length=50), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['sales_rep_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotations_customer_id'), 'quotations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_quotations_last_activity_at'), 'quotations', ['last_activity_at'], unique=False)
    op.create_index(op.f('ix_quotations_quotation_number'), 'quotations', ['quotation_number'], unique=True)
    op.create_index(op.f('ix_quotations_sales_rep_id'), 'quotations', ['sales_rep_id'], unique=False)
    op.create_index(op.f('ix_quotations_status'), 'quotations', ['status'], unique=False)
    op.create_table('approval_instances',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quotation_id', sa.Uuid(), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'REVISION_REQUIRED', name='approval_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_instances_quotation_id'), 'approval_instances', ['quotation_id'], unique=False)
    op.create_index(op.f('ix_approval_instances_status'), 'approval_instances', ['status'], unique=False)
    op.create_table('deal_alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quotation_id', sa.Uuid(), nullable=False),
    sa.Column('alert_type', sa.Enum('STALLED', 'DISCOUNT_ANOMALY', 'DELIVERY_SLIPPAGE', name='deal_alert_type'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='deal_alert_severity'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('metric_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('threshold_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', name='deal_alert_status'), nullable=False),
    sa.Column('action_taken', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_alerts_alert_type'), 'deal_alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_deal_alerts_quotation_id'), 'deal_alerts', ['quotation_id'], unique=False)
    op.create_index(op.f('ix_deal_alerts_status'), 'deal_alerts', ['status'], unique=False)
    op.create_table('negotiation_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quotation_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('requested_discount_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('requested_changes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'ACCEPTED', 'REJECTED', 'APPLIED', name='negotiation_request_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_negotiation_requests_customer_id'), 'negotiation_requests', ['customer_id'], unique=False)
    op.create_index(op.f('ix_negotiation_requests_quotation_id'), 'negotiation_requests', ['quotation_id'], unique=False)
    op.create_index(op.f('ix_negotiation_requests_requested_by'), 'negotiation_requests', ['requested_by'], unique=False)
    op.create_index(op.f('ix_negotiation_requests_status'), 'negotiation_requests', ['status'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_number', sa.String(length=100), nullable=False),
    sa.Column('quotation_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('CONFIRMED', 'FULFILLMENT', 'PARTIALLY_FULFILLED', 'FULFILLED', 'BILLING', 'COMPLETED', 'CANCELLED', name='order_status'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_orders_quotation_id'), 'orders', ['quotation_id'], unique=True)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('quotation_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quotation_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('margin_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('margin_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('allowed_discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('discount_excess_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotation_lines_product_id'), 'quotation_lines', ['product_id'], unique=False)
    op.create_index(op.f('ix_quotation_lines_quotation_id'), 'quotation_lines', ['quotation_id'], unique=False)
    op.create_index(op.f('ix_quotation_lines_variant_id'), 'quotation_lines', ['variant_id'], unique=False)
    op.create_table('approval_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('approval_instance_id', sa.Uuid(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('approver_role', sa.Enum('SALES_MANAGER', 'FINANCE_OPERATIONS', name='approver_role'), nullable=False),
    sa.Column('approver_user_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'REVISION_REQUIRED', name='approval_status'), nullable=False),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approval_instance_id'], ['approval_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['approver_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_steps_approval_instance_id'), 'approval_steps', ['approval_instance_id'], unique=False)
    op.create_index(op.f('ix_approval_steps_approver_user_id'), 'approval_steps', ['approver_user_id'], unique=False)
    op.create_index(op.f('ix_approval_steps_status'), 'approval_steps', ['status'], unique=False)
    op.create_table('backorders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('quotation_line_id', sa.Uuid(), nullable=False),
    sa.Column('quantity_backordered', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity_remaining', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CONSOLIDATION_AVAILABLE', 'CONSOLIDATED', 'FULFILLED', 'CANCELLED', name='backorder_status'), nullable=False),
    sa.Column('consolidation_requested', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quotation_line_id'], ['quotation_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backorders_order_id'), 'backorders', ['order_id'], unique=False)
    op.create_index(op.f('ix_backorders_quotation_line_id'), 'backorders', ['quotation_line_id'], unique=False)
    op.create_index(op.f('ix_backorders_status'), 'backorders', ['status'], unique=False)
    op.create_table('fulfillment_allocations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('quotation_line_id', sa.Uuid(), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('quantity_allocated', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity_fulfilled', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estimated_shipping_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_suggested', sa.Boolean(), nullable=False),
    sa.Column('is_manual_override', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('SUGGESTED', 'ACCEPTED', 'FULFILLED', 'CANCELLED', name='fulfillment_allocation_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quotation_line_id'], ['quotation_lines.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fulfillment_allocations_order_id'), 'fulfillment_allocations', ['order_id'], unique=False)
    op.create_index(op.f('ix_fulfillment_allocations_quotation_line_id'), 'fulfillment_allocations', ['quotation_line_id'], unique=False)
    op.create_index(op.f('ix_fulfillment_allocations_status'), 'fulfillment_allocations', ['status'], unique=False)
    op.create_index(op.f('ix_fulfillment_allocations_warehouse_id'), 'fulfillment_allocations', ['warehouse_id'], unique=False)
    op.create_table('negotiation_comments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quotation_id', sa.Uuid(), nullable=False),
    sa.Column('quotation_line_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quotation_line_id'], ['quotation_lines.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_negotiation_comments_quotation_id'), 'negotiation_comments', ['quotation_id'], unique=False)
    op.create_index(op.f('ix_negotiation_comments_quotation_line_id'), 'negotiation_comments', ['quotation_line_id'], unique=False)
    op.create_index(op.f('ix_negotiation_comments_user_id'), 'negotiation_comments', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('quotation_line_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('next_billing_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'MODIFIED', 'CANCELLED', 'PAUSED', name='subscription_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['quotation_line_id'], ['quotation_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_customer_id'), 'subscriptions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_next_billing_date'), 'subscriptions', ['next_billing_date'], unique=False)
    op.create_index(op.f('ix_subscriptions_order_id'), 'subscriptions', ['order_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_plan_id'), 'subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_product_id'), 'subscriptions', ['product_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_quotation_line_id'), 'subscriptions', ['quotation_line_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_table('billing_schedules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=False),
    sa.Column('billing_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'INVOICED', 'PAID', 'CANCELLED', name='billing_schedule_status'), nullable=False),
    sa.Column('proration_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_schedules_billing_date'), 'billing_schedules', ['billing_date'], unique=False)
    op.create_index(op.f('ix_billing_schedules_status'), 'billing_schedules', ['status'], unique=False)
    op.create_index(op.f('ix_billing_schedules_subscription_id'), 'billing_schedules', ['subscription_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('billing_schedule_id', sa.Uuid(), nullable=True),
    sa.Column('invoice_type', sa.Enum('ONE_TIME', 'RECURRING', 'CREDIT_NOTE', name='invoice_type'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ISSUED', 'PARTIALLY_PAID', 'PAID', 'CANCELLED', name='invoice_status'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['billing_schedule_id'], ['billing_schedules.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_billing_schedule_id'), 'invoices', ['billing_schedule_id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_order_id'), 'invoices', ['order_id'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=100), nullable=False),
    sa.Column('transaction_reference', sa.String(length=255), nullable=True),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('RECORDED', 'FAILED', 'REFUNDED', name='payment_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_order_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_billing_schedule_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_billing_schedules_subscription_id'), table_name='billing_schedules')
    op.drop_index(op.f('ix_billing_schedules_status'), table_name='billing_schedules')
    op.drop_index(op.f('ix_billing_schedules_billing_date'), table_name='billing_schedules')
    op.drop_table('billing_schedules')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_quotation_line_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_product_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_plan_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_order_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_next_billing_date'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_customer_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_negotiation_comments_user_id'), table_name='negotiation_comments')
    op.drop_index(op.f('ix_negotiation_comments_quotation_line_id'), table_name='negotiation_comments')
    op.drop_index(op.f('ix_negotiation_comments_quotation_id'), table_name='negotiation_comments')
    op.drop_table('negotiation_comments')
    op.drop_index(op.f('ix_fulfillment_allocations_warehouse_id'), table_name='fulfillment_allocations')
    op.drop_index(op.f('ix_fulfillment_allocations_status'), table_name='fulfillment_allocations')
    op.drop_index(op.f('ix_fulfillment_allocations_quotation_line_id'), table_name='fulfillment_allocations')
    op.drop_index(op.f('ix_fulfillment_allocations_order_id'), table_name='fulfillment_allocations')
    op.drop_table('fulfillment_allocations')
    op.drop_index(op.f('ix_backorders_status'), table_name='backorders')
    op.drop_index(op.f('ix_backorders_quotation_line_id'), table_name='backorders')
    op.drop_index(op.f('ix_backorders_order_id'), table_name='backorders')
    op.drop_table('backorders')
    op.drop_index(op.f('ix_approval_steps_status'), table_name='approval_steps')
    op.drop_index(op.f('ix_approval_steps_approver_user_id'), table_name='approval_steps')
    op.drop_index(op.f('ix_approval_steps_approval_instance_id'), table_name='approval_steps')
    op.drop_table('approval_steps')
    op.drop_index(op.f('ix_quotation_lines_variant_id'), table_name='quotation_lines')
    op.drop_index(op.f('ix_quotation_lines_quotation_id'), table_name='quotation_lines')
    op.drop_index(op.f('ix_quotation_lines_product_id'), table_name='quotation_lines')
    op.drop_table('quotation_lines')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_quotation_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_negotiation_requests_status'), table_name='negotiation_requests')
    op.drop_index(op.f('ix_negotiation_requests_requested_by'), table_name='negotiation_requests')
    op.drop_index(op.f('ix_negotiation_requests_quotation_id'), table_name='negotiation_requests')
    op.drop_index(op.f('ix_negotiation_requests_customer_id'), table_name='negotiation_requests')
    op.drop_table('negotiation_requests')
    op.drop_index(op.f('ix_deal_alerts_status'), table_name='deal_alerts')
    op.drop_index(op.f('ix_deal_alerts_quotation_id'), table_name='deal_alerts')
    op.drop_index(op.f('ix_deal_alerts_alert_type'), table_name='deal_alerts')
    op.drop_table('deal_alerts')
    op.drop_index(op.f('ix_approval_instances_status'), table_name='approval_instances')
    op.drop_index(op.f('ix_approval_instances_quotation_id'), table_name='approval_instances')
    op.drop_table('approval_instances')
    op.drop_index(op.f('ix_quotations_status'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_sales_rep_id'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_quotation_number'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_last_activity_at'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_customer_id'), table_name='quotations')
    op.drop_table('quotations')
    op.drop_index(op.f('ix_price_list_items_variant_id'), table_name='price_list_items')
    op.drop_index(op.f('ix_price_list_items_product_id'), table_name='price_list_items')
    op.drop_index(op.f('ix_price_list_items_price_list_id'), table_name='price_list_items')
    op.drop_index('ix_price_list_items_list_product', table_name='price_list_items')
    op.drop_table('price_list_items')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_refresh_token_hash'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_customer_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_recommendation_rules_source_product_id'), table_name='recommendation_rules')
    op.drop_index(op.f('ix_recommendation_rules_recommended_product_id'), table_name='recommendation_rules')
    op.drop_table('recommendation_rules')
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index(op.f('ix_inventory_warehouse_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_product_id'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_price_lists_customer_tier_id'), table_name='price_lists')
    op.drop_table('price_lists')
    op.drop_index(op.f('ix_discount_rules_customer_tier_id'), table_name='discount_rules')
    op.drop_index(op.f('ix_discount_rules_category_id'), table_name='discount_rules')
    op.drop_table('discount_rules')
    op.drop_index(op.f('ix_customers_customer_tier_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_warehouses_code'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_table('subscription_plans')
    op.drop_table('product_categories')
    op.drop_table('customer_tiers')
    op.drop_table('approval_policies')

    # Drop PostgreSQL enum types created by initial_schema
    for enum_name in [
        'payment_status',
        'invoice_status',
        'invoice_type',
        'billing_schedule_status',
        'subscription_status',
        'fulfillment_allocation_status',
        'backorder_status',
        'approver_role',
        'order_status',
        'negotiation_request_status',
        'deal_alert_status',
        'deal_alert_severity',
        'deal_alert_type',
        'approval_status',
        'quotation_status',
        'recommendation_type',
        'proration_method',
        'billing_interval',
    ]:
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
